# Generated by Django 4.2.4 on 2023-08-03 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='Proveedor',
            new_name='proveedor',
        ),
    ]
