# Generated by Django 4.2.4 on 2023-08-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(default='users/img_perfiles/github-icon-design-vector-png_115671.jpg', upload_to='users/img_perfiles'),
        ),
    ]
